[package]
name = "able-editor"
version = "0.1.0"
authors = ["Able <abl3theabove@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "*"
home = "0.5.3"
log="*"
